### ISSUE TITLE
49. Group Anagrams

### ISSUE THREAD

**Issue by smamodia** [Hsinha11/Leetcode-solutions#25]
Problem Statement: Given an array of strings strs, group the anagrams together. You can return the answer in any order.
This problem is not there in your repository. I would like to add it. Please assign it to me.

**Comment by Taj-2005** [comment]
please assign this task to me for hacktoberfest2024

**Comment by Hsinha11** [comment]
> please assign this task to me for hacktoberfest2024

You can go for any other question on leetcode, I will assign that to you, For this one, I will assign to @smamodia

**Comment by smamodia** [comment]
Thanks you @Hsinha11
