### ISSUE TITLE
202. Happy Number (Easy)

### ISSUE THREAD

**Issue by danieltayal07** [Hsinha11/Leetcode-solutions#26]
Write an algorithm to determine if a number n is happy.

A happy number is a number defined by the following process:

Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.
Return true if n is a happy number, and false if not.

Please assign me this problem under hacktoberfest2024!
please consider the pull request i have requested for the same under hacktoberfest2024 if found contributive
Thanks!

**Comment by ashrith-07** [comment]
Please assign this task to me for hacktoberfest2024

**Comment by danieltayal07** [comment]
hey @ashrith-07 
actually i created this issue along with my pull request of the problem.

**Comment by Hsinha11** [comment]
assigning it to you @danieltayal07

**Comment by Hsinha11** [comment]
Merged the PR, closing this issue now
