### ISSUE TITLE
 31. Next Permutation

### ISSUE THREAD

**Issue by vaishvi2811** [Hsinha11/Leetcode-solutions#56]
Problem : Given an array arr[ ] of integers, rearrange the numbers of the given array into the lexicographically next greater permutation of numbers. If such an arrangement is not possible, it must rearrange to the lowest possible order (i.e., sorted in ascending order).
Example: 
Input: nums = [1,2,3]
Output: [1,3,2]

link: https://leetcode.com/problems/next-permutation/

I would like to work on this, please assign.

**Comment by Hsinha11** [comment]
star the repo and make a PR
