### ISSUE TITLE
REVERSE INTEGER

### ISSUE THREAD

**Issue by janviisonii23** [Hsinha11/Leetcode-solutions#73]
## PROBELM - 7. Reverse Integer
* Would be given a integer positive or negetive we have to reverse it keeping the sign and the reversed number should not have any trailing zeros and reversed number should not be more than a 32 but bit signed or unsigned approach.
## APROACH
* First we check if it is a negetive integer we remove the negetive sign and then we continue.
* Then we extract each digit of the input integer and store them in a vector in reverse order and removing any trailing zeros
* Then we concatenate these reversed digits into a string (num) to form the reversed number.
* Then we convert num to an integer . If this results in an overflow (out of 32-bit integer range), it catches the exception and returns 0.
* If the input was initially negative, it negates the reversed integer before returning it.

This is my approach please assign me this issue.

**Comment by Hsinha11** [comment]
Assigned you with the issue, make a PR, link the PR to this issue  and I shall merge it. 
Make sure to star the repo

**Comment by FaheemorFAB** [comment]
PR FIXES issue #73
Create -7-Reverse_Integer.c #106
