### ISSUE TITLE
46. Permutations

### ISSUE THREAD

**Issue by KrishShah3011** [Hsinha11/Leetcode-solutions#76]
Allow me to add the solution the problem number 46. Permutations on Leet Code

Approach: 
The solution generates all permutations of a list of integers using recursion. If the input list has only one element, it returns that element as a permutation. Otherwise, it iteratively removes the first element n, recursively finds permutations of the remaining list, and appends n to each permutation. These modified permutations are added to the result. After each iteration, the removed element is re-added to restore the original list for the next iteration, ensuring all permutations are covered.

Please assign me this issue.

**Comment by KrishShah3011** [comment]
hey can you add the hacktober tags to the issue

**Comment by Hsinha11** [comment]
Done, merged the PR ,you can check the status of the PR
