### ISSUE TITLE
2.  Add Two Numbers

### ISSUE THREAD

**Issue by Sohamshah03** [Hsinha11/Leetcode-solutions#78]
You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

**Comment by Sohamshah03** [comment]
Please assign me this issue.

**Comment by FaheemorFAB** [comment]
Fixed PR -Create -2-Add_Two_Numbers.py #100
