### ISSUE TITLE
Search A 2D Array

### ISSUE THREAD

**Issue by harshogale04** [Hsinha11/Leetcode-solutions#84]
You are given an m x n integer matrix matrix with the following two properties:

Each row is sorted in non-decreasing order.
The first integer of each row is greater than the last integer of the previous row.
Given an integer target, return true if target is in matrix or false otherwise.

You must write a solution in O(log(m * n)) time complexity.

Also pls assign tags. Thank you

**Comment by Hsinha11** [comment]
Fix the PR, add proper readme , and add it in a file structure
