### ISSUE TITLE
575. Distribute Candies

### ISSUE THREAD

**Issue by Kaos599** [Hsinha11/Leetcode-solutions#90]
## Problem 

Alice has n candies, where the ith candy is of type candyType[i]. Alice noticed that she started to gain weight, so she visited a doctor.
The doctor advised Alice to only eat n / 2 of the candies she has (n is always even). Alice likes her candies very much, and she wants to eat the maximum number of different types of candies while still following the doctor's advice.
Given the integer array candyType of length n, return the maximum number of different types of candies she can eat if she only eats n / 2 of them.

## Approach to Solution
First, I initialize an unordered set. This set is constructed using the elements from the candyType vector. By doing so, I ensure that only unique types of candies are stored, effectively eliminating any duplicates.

Next, I calculate the maximum types of candies Alice can consume, stored in the variable . This is done by utilizing the min function, which compares the size of the uniqueCandies set and half the size of the candyType vector (candyType.size() / 2). This ensures Alice adheres to the doctor's advice while maximizing the diversity of candies she can enjoy.

Finally, the value is returned.

## Additional notes
Can you please assign this to me and also label it for hacktoberfest?

**Comment by FaheemorFAB** [comment]
Assign this to me plz

**Comment by FaheemorFAB** [comment]
DONE Create -575-Distribute_Candies,py #105
