### ISSUE TITLE
26.Remove Duplicates from Sorted Array

### ISSUE THREAD

**Issue by janviisonii23** [Hsinha11/Leetcode-solutions#95]
* Given an integer array nums sorted in non-decreasing order, remove the duplicates [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) such that each unique element appears only once. The relative order of the elements should be kept the same. Then return the number of unique elements in nums.

* Consider the number of unique elements of nums to be k, to get accepted, you need to do the following things:

* Change the array nums such that the first k elements of nums contain the unique elements in the order they were present in nums initially.
*  The remaining elements of nums are not important as well as the size of nums.
* Return k.

Can you assign me this issue.

**Comment by Hsinha11** [comment]
just make a PR
