### ISSUE TITLE
Anagram-Leetcode-Solution

### ISSUE THREAD

**Issue by AmriteshRaj123** [Hsinha11/Leetcode-solutions#96]
An anagram of a string is a rearrangement of its letters to form another word or phrase, using all original letters exactly once.

**Comment by AmriteshRaj123** [comment]
@Hsinha11    I would love the opportunity to contribute and work on this project.
Could you please assign the issue to me? I'm eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by FaheemorFAB** [comment]
Assign it to me
please
